import { useState } from 'react'
import { useWallet } from '@/hooks/useWallet'
import { useGameStore } from '@/stores/gameStore'
import { useBetHistory } from '@/hooks/useBetHistory'
import { Card } from '@/components/common/Card'
import { ConnectButton } from '@/components/wallet/ConnectButton'
import { BetForm } from '@/components/game/BetForm'
import { DiceResultPanel } from '@/components/game/ResultPanel'
import { BetHistory } from '@/components/game/BetHistory'

export default function DicePage() {
  const { address, isConnected } = useWallet()
  const { diceBets, pokerBets } = useGameStore()
  const [activeBetId, setActiveBetId] = useState<bigint | null>(null)

  useBetHistory(address)

  const activeBet = activeBetId ? diceBets.get(activeBetId) : null

  if (!isConnected) {
    return (
      <div className="text-center py-16">
        <div className="text-6xl mb-4">🎲</div>
        <h1 className="text-4xl font-bold mb-4">Dice Game</h1>
        <p className="text-gray-400 mb-8">Connect your wallet to start playing</p>
        <div className="flex justify-center"><ConnectButton /></div>
      </div>
    )
  }

  return (
    <div>
      <h1 className="text-3xl font-bold mb-8">🎲 Dice Game</h1>

      <div className="grid lg:grid-cols-2 gap-8">
        <div>
          <BetForm gameType="dice" onBetPlaced={setActiveBetId} />
        </div>

        <div>
          {activeBet ? (
            <DiceResultPanel bet={activeBet} />
          ) : (
            <Card>
              <h3 className="text-lg font-bold mb-4">How to Play</h3>
              <ul className="space-y-3 text-gray-400">
                <li className="flex gap-2">
                  <span className="text-blue-400">1.</span>
                  Choose your bet amount and multiplier
                </li>
                <li className="flex gap-2">
                  <span className="text-blue-400">2.</span>
                  A random number (1-100) is generated by Chainlink VRF
                </li>
                <li className="flex gap-2">
                  <span className="text-blue-400">3.</span>
                  You win if the result exceeds the threshold
                </li>
              </ul>

              <div className="mt-6 space-y-2">
                <h4 className="text-sm font-semibold text-gray-300">Win Conditions</h4>
                <div className="grid grid-cols-3 gap-2 text-center text-sm">
                  <div className="bg-gray-700/50 rounded p-2">
                    <div className="font-bold text-blue-400">2x</div>
                    <div className="text-gray-400">Roll &gt; 50</div>
                    <div className="text-xs text-gray-500">50% chance</div>
                  </div>
                  <div className="bg-gray-700/50 rounded p-2">
                    <div className="font-bold text-blue-400">5x</div>
                    <div className="text-gray-400">Roll &gt; 80</div>
                    <div className="text-xs text-gray-500">20% chance</div>
                  </div>
                  <div className="bg-gray-700/50 rounded p-2">
                    <div className="font-bold text-blue-400">10x</div>
                    <div className="text-gray-400">Roll &gt; 90</div>
                    <div className="text-xs text-gray-500">10% chance</div>
                  </div>
                </div>
              </div>
            </Card>
          )}
        </div>
      </div>

      <div className="mt-12">
        <h2 className="text-2xl font-bold mb-4">Your Dice History</h2>
        <BetHistory
          diceBets={Array.from(diceBets.values())}
          pokerBets={Array.from(pokerBets.values())}
          filter="dice"
        />
      </div>
    </div>
  )
}
